export const deleteButton = () => cy.get('[data-cy=delete-button]')
export const coursesLink = () => cy.get('[data-cy=courses]')
export const newCourseInput = () => cy.get('[data-cy=new-task-input]')
export const newCourseButton = () => cy.get('[data-cy=new-task-button]')
export const courseName = () => cy.get('[data-cy=course-name]')